services:
  backend:
    build: ./backend
    container_name: pokemon-backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      FRONTEND_URL: https://hortifrut-frontend.alejandropch.com
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pokemon-frontend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://hortifrut-backend.alejandropch.com
    restart: unless-stopped

